[loggers]
keys=root,serverOPC, clientModbus, opcToFiware

[handlers]
keys=fileHandler, fileHandler2, fileHandler3

[formatters]
keys=simpleFormatter

[logger_root]
level=ERROR
handlers=fileHandler
qualname=root

[logger_serverOPC]
level=INFO
handlers=fileHandler
qualname=serverOPC
propagate=0

[logger_clientModbus]
level=INFO
handlers=fileHandler2
qualname=clientModbus
propagate=0

[logger_opcToFiware]
level=INFO
handlers=fileHandler3
qualname=opcToFiware
propagate=0

[handler_fileHandler]
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=INFO
formatter=simpleFormatter
args=('tasks/logServer/ServerOPC.log', 'a', 1024 * 1024, 5) 

[handler_fileHandler2]
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=INFO
formatter=simpleFormatter
args=('tasks/logModbus/Modbus.log', 'a', 1024*1024, 5)

[handler_fileHandler3]
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=INFO
formatter=simpleFormatter
args=('tasks/logOPCtoFIWARE/OPCtoFIWARE.log', 'a', 1024*1024, 5)

[formatter_simpleFormatter]
format='%(levelname)s:%(asctime)s %(message)s'
datefmt='%d/%m/%Y %I:%M:%S %p'
